/* Pop Culture — product catalog.
 * Images map to the real files provided in the repo root. */

window.__POPCULTURE_DATA__ = (function () {
  const img = (n) => n; // images live in root, referenced relatively

  const products = [
    {
      id: "pc-001",
      slug: "hulk-smash-box-tee",
      name: "Hulk Smash Box Tee",
      price: 1299, mrp: 1799,
      category: "Movies",
      tags: ["bestseller"],
      images: ["01_33.jpg", "02_31.jpg", "03_30.jpg"],
      sizes: ["S", "M", "L", "XL", "XXL"],
      colors: ["Black"],
      rating: 4.8, reviewCount: 312,
      description:
        "Oversized 240 GSM cotton tee featuring a Marvel box print. Enzyme-washed for that lived-in feel. Drop shoulder cut. Printed in Gurugram.",
      highlights: ["240 GSM heavyweight cotton", "Drop-shoulder oversized fit", "Water-based DTF print", "Pre-shrunk"],
    },
    {
      id: "pc-002",
      slug: "neon-tokyo-oversized",
      name: "Neon Tokyo Oversized Tee",
      price: 1499, mrp: 1999,
      category: "Anime",
      tags: ["bestseller", "new"],
      images: ["67_8.jpg", "67_9.jpg", "67_10_f9674373-ceda-4403-942e-b5b71426396a.jpg"],
      sizes: ["S", "M", "L", "XL", "XXL"],
      colors: ["Cream"],
      rating: 4.9, reviewCount: 428,
      description:
        "A love letter to Shibuya nights. Back-printed Maneki-neko graphic with katakana typography on a soft cream body.",
      highlights: ["All-over graphic back print", "Heavy 240 GSM cotton", "Boxy oversized silhouette"],
    },
    {
      id: "pc-003",
      slug: "retro-arcade-tee",
      name: "Retro Arcade Tee",
      price: 1199, mrp: 1599,
      category: "Gaming",
      tags: ["new"],
      images: ["67_11.jpg", "67_12.jpg"],
      sizes: ["S", "M", "L", "XL"],
      colors: ["Off-White"],
      rating: 4.7, reviewCount: 156,
      description: "A pixel-perfect tribute to 90s arcade culture. Soft combed cotton, clean relaxed fit.",
      highlights: ["200 GSM combed cotton", "Relaxed fit", "Vintage-style print"],
    },
    {
      id: "pc-004",
      slug: "bollywood-bass-tee",
      name: "Bollywood Bass Tee",
      price: 1099, mrp: 1499,
      category: "Music",
      tags: ["bestseller"],
      images: ["67_13.jpg", "67_15.jpg"],
      sizes: ["S", "M", "L", "XL", "XXL"],
      colors: ["Black"],
      rating: 4.6, reviewCount: 201,
      description: "Desi hip-hop energy. Heavyweight cotton, puff-print Devanagari typography.",
      highlights: ["Puff print detail", "Heavy 240 GSM", "Drop shoulder"],
    },
    {
      id: "pc-005",
      slug: "meme-mode-tee",
      name: "Meme Mode Tee",
      price: 999, mrp: 1399,
      category: "Memes",
      tags: [],
      images: ["67_16.jpg", "67_17.jpg"],
      sizes: ["S", "M", "L", "XL"],
      colors: ["White"],
      rating: 4.5, reviewCount: 98,
      description: "For the timeline scrollers. Ironic graphic front, clean back.",
      highlights: ["Lightweight 180 GSM", "Regular fit"],
    },
    {
      id: "pc-006",
      slug: "midnight-ronin-tee",
      name: "Midnight Ronin Tee",
      price: 1599, mrp: 2199,
      category: "Anime",
      tags: ["limited", "bestseller"],
      images: ["Artboard14_37.jpg", "Artboard15_37.jpg"],
      sizes: ["M", "L", "XL"],
      colors: ["Black"],
      rating: 4.9, reviewCount: 512,
      description: "Limited drop. Samurai back-graphic tee with metallic ink detailing.",
      highlights: ["Limited 300 units", "Metallic ink accents", "Heavy 260 GSM"],
    },
    {
      id: "pc-007",
      slug: "grunge-band-tour-tee",
      name: "Grunge Band Tour Tee",
      price: 1299, mrp: 1799,
      category: "Music",
      tags: ["new"],
      images: ["Artboard16_10_d2e736f4-b1bf-4973-82ab-0d0f7702cd59.jpg", "Artboard17_11_2de42146-7bc0-48c3-aa9b-c7930706dcef.jpg"],
      sizes: ["S", "M", "L", "XL", "XXL"],
      colors: ["Black"],
      rating: 4.7, reviewCount: 183,
      description: "Vintage tour-tee vibes. Distressed print, acid-washed feel.",
      highlights: ["Acid wash finish", "Distressed print", "Cotton blend"],
    },
    {
      id: "pc-008",
      slug: "cyberpunk-2099-tee",
      name: "Cyberpunk 2099 Tee",
      price: 1699, mrp: 2299,
      category: "Gaming",
      tags: ["limited"],
      images: ["Artboard19_67.jpg", "Artboard20_62.jpg"],
      sizes: ["M", "L", "XL"],
      colors: ["Black"],
      rating: 4.8, reviewCount: 267,
      description: "Neon-drenched dystopia. Reflective ink that glows under UV light.",
      highlights: ["Reflective ink print", "Heavy 250 GSM", "Limited edition"],
    },
    {
      id: "pc-009",
      slug: "kaiju-kingdom-tee",
      name: "Kaiju Kingdom Tee",
      price: 1399, mrp: 1899,
      category: "Anime",
      tags: ["bestseller"],
      images: ["Artboard21_56.jpg", "Artboard22_55.jpg"],
      sizes: ["S", "M", "L", "XL", "XXL"],
      colors: ["Cream"],
      rating: 4.8, reviewCount: 342,
      description: "Giant monster back print with hand-drawn detailing.",
      highlights: ["Hand-illustrated artwork", "240 GSM cotton", "Oversized fit"],
    },
    {
      id: "pc-010",
      slug: "skate-or-die-tee",
      name: "Skate Or Die Tee",
      price: 1099, mrp: 1499,
      category: "Streetwear",
      tags: ["new"],
      images: ["Artboard24_20.jpg", "Artboard_20_16.jpg"],
      sizes: ["S", "M", "L", "XL"],
      colors: ["White"],
      rating: 4.6, reviewCount: 124,
      description: "Pure street energy. Double-print front and back.",
      highlights: ["Front & back print", "Regular fit", "200 GSM"],
    },
    {
      id: "pc-011",
      slug: "cosmic-drifter-tee",
      name: "Cosmic Drifter Tee",
      price: 1499, mrp: 1999,
      category: "Movies",
      tags: ["bestseller"],
      images: ["Artboard26_2_c3ed6588-164f-4e3c-80c9-eccbf1bc3a8c.jpg", "Artboard27_2.jpg"],
      sizes: ["S", "M", "L", "XL", "XXL"],
      colors: ["Navy"],
      rating: 4.9, reviewCount: 389,
      description: "Sci-fi inspired back graphic. Premium heavyweight fabric.",
      highlights: ["Back graphic", "260 GSM", "Drop shoulder"],
    },
    {
      id: "pc-012",
      slug: "lowkey-legend-tee",
      name: "Lowkey Legend Tee",
      price: 999, mrp: 1399,
      category: "Streetwear",
      tags: [],
      images: ["Artboard31_44.jpg", "Artboard_25_19.jpg"],
      sizes: ["S", "M", "L", "XL"],
      colors: ["Beige"],
      rating: 4.5, reviewCount: 87,
      description: "Minimal graphic, maximum vibe.",
      highlights: ["Minimalist design", "Soft cotton", "Relaxed fit"],
    },
    {
      id: "pc-013",
      slug: "vhs-static-tee",
      name: "VHS Static Tee",
      price: 1199, mrp: 1599,
      category: "Movies",
      tags: ["new"],
      images: ["Artboard5-2026-02-19T183213.204.jpg", "Artboard6-2026-02-19T183215.185.jpg"],
      sizes: ["S", "M", "L", "XL"],
      colors: ["Black"],
      rating: 4.7, reviewCount: 142,
      description: "Glitched-out retro tape aesthetic. Oversized drop shoulder.",
      highlights: ["Glitch graphic", "240 GSM", "Oversized"],
    },
    {
      id: "pc-014",
      slug: "bass-drop-tee",
      name: "Bass Drop Tee",
      price: 1299, mrp: 1799,
      category: "Music",
      tags: ["bestseller"],
      images: ["Artboard7-2026-02-19T183216.539.jpg", "Artboard8-2026-02-19T183218.378.jpg"],
      sizes: ["M", "L", "XL", "XXL"],
      colors: ["Black"],
      rating: 4.8, reviewCount: 223,
      description: "Audio-wave graphic print for the rave crowd.",
      highlights: ["Glow-in-dark accent", "Heavy cotton", "Oversized"],
    },
    {
      id: "pc-015",
      slug: "trippy-thoughts-tee",
      name: "Trippy Thoughts Tee",
      price: 1099, mrp: 1499,
      category: "Memes",
      tags: ["new"],
      images: ["Artboard_2_-_2026-02-26T095337.475.jpg", "Artboard_3_-_2026-02-26T095339.878.jpg"],
      sizes: ["S", "M", "L", "XL"],
      colors: ["White"],
      rating: 4.6, reviewCount: 109,
      description: "Psychedelic graphic tee for overthinkers.",
      highlights: ["Saturated print", "200 GSM", "Regular fit"],
    },
    {
      id: "pc-016",
      slug: "street-signal-tee",
      name: "Street Signal Tee",
      price: 1199, mrp: 1599,
      category: "Streetwear",
      tags: [],
      images: ["Artboard_4_45.jpg", "Artboard_5_35.jpg"],
      sizes: ["S", "M", "L", "XL"],
      colors: ["Grey"],
      rating: 4.5, reviewCount: 76,
      description: "Utility-inspired graphic tee with bold typography.",
      highlights: ["Heavy cotton", "Utility print"],
    },
    {
      id: "pc-017",
      slug: "mech-soul-tee",
      name: "Mech Soul Tee",
      price: 1599, mrp: 2199,
      category: "Anime",
      tags: ["limited"],
      images: ["Artboard_56_2.jpg", "Artboard_57_3.jpg"],
      sizes: ["M", "L", "XL"],
      colors: ["Olive"],
      rating: 4.9, reviewCount: 287,
      description: "Mech anime cover art on heavyweight cotton. Limited drop.",
      highlights: ["Limited 250 units", "Back graphic", "260 GSM"],
    },
    {
      id: "pc-018",
      slug: "4am-thoughts-tee",
      name: "4AM Thoughts Tee",
      price: 1099, mrp: 1499,
      category: "Memes",
      tags: [],
      images: ["Artboard_58_2.jpg", "Artboard_59_2.jpg"],
      sizes: ["S", "M", "L", "XL"],
      colors: ["Black"],
      rating: 4.4, reviewCount: 64,
      description: "Late-night thoughts, worn proudly.",
      highlights: ["200 GSM", "Regular fit"],
    },
    {
      id: "pc-019",
      slug: "grid-breaker-tee",
      name: "Grid Breaker Tee",
      price: 1299, mrp: 1799,
      category: "Streetwear",
      tags: ["new"],
      images: ["Artboard_64_3.jpg", "Artboard_65_2.jpg"],
      sizes: ["S", "M", "L", "XL", "XXL"],
      colors: ["White"],
      rating: 4.7, reviewCount: 112,
      description: "Architectural graphic print. Futuristic streetwear fit.",
      highlights: ["Vector print", "240 GSM", "Oversized"],
    },
    {
      id: "pc-020",
      slug: "last-level-tee",
      name: "Last Level Tee",
      price: 1399, mrp: 1899,
      category: "Gaming",
      tags: ["bestseller"],
      images: ["Artboard_66_3.jpg", "Artboard_67_3.jpg"],
      sizes: ["S", "M", "L", "XL"],
      colors: ["Black"],
      rating: 4.8, reviewCount: 231,
      description: "For the final-boss crowd. Glowing pixel art print.",
      highlights: ["UV-reactive ink", "Heavy cotton"],
    },
    {
      id: "pc-021",
      slug: "dream-static-tee",
      name: "Dream Static Tee",
      price: 1199, mrp: 1599,
      category: "Music",
      tags: [],
      images: ["04_26.jpg", "05_32.jpg"],
      sizes: ["S", "M", "L", "XL"],
      colors: ["Cream"],
      rating: 4.6, reviewCount: 93,
      description: "Dreamy, analog-inspired band graphic.",
      highlights: ["Vintage wash", "220 GSM"],
    },
    {
      id: "pc-022",
      slug: "icon-archive-tee",
      name: "Icon Archive Tee",
      price: 1499, mrp: 1999,
      category: "Movies",
      tags: ["new"],
      images: ["1_0003_GenerativeFill3_c55e69a9-8e49-403c-b2e8-631d82c8a906.jpg", "1_0004_GenerativeFill4_9c0ad45c-d2ba-45ea-8aaf-f5288d4e4ee3.jpg"],
      sizes: ["S", "M", "L", "XL", "XXL"],
      colors: ["Black"],
      rating: 4.8, reviewCount: 178,
      description: "Homage to cult film posters. Premium heavy cotton.",
      highlights: ["Archive print", "Heavy 250 GSM"],
    },
    {
      id: "pc-023",
      slug: "wavy-signal-tee",
      name: "Wavy Signal Tee",
      price: 1099, mrp: 1499,
      category: "Memes",
      tags: [],
      images: ["1_0006_1_7d720efe-0446-44d2-9692-d1d68a7cb50e.jpg", "01_3_11ddc42c-0a77-41c0-a984-c90938510471.jpg"],
      sizes: ["S", "M", "L", "XL"],
      colors: ["White"],
      rating: 4.4, reviewCount: 58,
      description: "Glitchy, wavy, absurd — just like the timeline.",
      highlights: ["Saturated print", "Regular fit"],
    },
    {
      id: "pc-024",
      slug: "after-hours-tee",
      name: "After Hours Tee",
      price: 1599, mrp: 2199,
      category: "Music",
      tags: ["limited"],
      images: ["Artboard_4_89.jpg", "Artboard_5_69.jpg"],
      sizes: ["M", "L", "XL"],
      colors: ["Black"],
      rating: 4.9, reviewCount: 302,
      description: "Limited run drop. Glow accents for the after-hours crowd.",
      highlights: ["Limited edition", "Glow ink detailing"],
    },
  ];

  const collections = [
    { name: "Anime", tagline: "From Shonen to Seinen", image: "67_8.jpg", slug: "Anime" },
    { name: "Movies", tagline: "Cult classics reborn", image: "Artboard26_2_c3ed6588-164f-4e3c-80c9-eccbf1bc3a8c.jpg", slug: "Movies" },
    { name: "Music", tagline: "Tour tees, reimagined", image: "Artboard7-2026-02-19T183216.539.jpg", slug: "Music" },
    { name: "Memes", tagline: "For the chronically online", image: "Artboard_2_-_2026-02-26T095337.475.jpg", slug: "Memes" },
    { name: "Gaming", tagline: "Press start", image: "Artboard19_67.jpg", slug: "Gaming" },
    { name: "Streetwear", tagline: "Off-grid essentials", image: "Artboard24_20.jpg", slug: "Streetwear" },
  ];

  const testimonials = [
    { name: "Aditi R.", location: "Bengaluru", rating: 5, text: "Fit is chef's kiss. Got compliments on Day 1. Heavyweight cotton is a vibe." },
    { name: "Rohan M.", location: "Mumbai", rating: 5, text: "Finally — a desi brand that actually gets streetwear. The anime tee is unreal." },
    { name: "Priya S.", location: "Delhi NCR", rating: 5, text: "Bought 3 tees. Quality survives 20+ washes. Prints still bright. 10/10." },
    { name: "Kabir D.", location: "Gurugram", rating: 4, text: "Love the oversized fit. Drops sell out fast — set alarms. Worth the hype." },
    { name: "Anaya V.", location: "Pune", rating: 5, text: "The Midnight Ronin tee is art. The metallic ink detail is next level." },
    { name: "Veer K.", location: "Hyderabad", rating: 5, text: "Heavy cotton, clean cuts, bold prints. Exactly what I wanted." },
  ];

  return { products, collections, testimonials };
})();
